### ISSUE TITLE
[Chore] 프로젝트 세팅

### ISSUE THREAD

**Issue by hope1053** [mash-up-kr/gabbangzip-iOS#1]
## 🚀 Description
프로젝트 세팅을 합니다!

## ✅ TODO
- [x] Issue template 설정 (Feature, Bug)
- [x] PR Template 설정
- [x] Git ignore 설정
- [x] PR Autoassign 설정
