### ISSUE TITLE
[Feature] 이미지 비율 변경

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#102]
## 🚀 Description
- 이미지 비율 변경(`scaledToFit` -> `aspectRatio(fill)`)

## ✅ TODO
- [ ] 이미지 비율 변경(`scaledToFit` -> `aspectRatio(fill)`)
  - [ ] 그룹 목록 화면
  - [ ] 그룹 만들기의 사진 고르기 화면
  - [ ] 그룹 만들기의 완료 화면

## 📸 Screenshot(optional)
<img src="https://github.com/user-attachments/assets/ce3876f3-3f67-4fb9-8619-c9f5ae2002c0" width="200" height="450">
