### ISSUE TITLE
[Feat] 홈 화면 리팩토링 및 API연동

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#111]
## 🚀 Description
- 홈 화면의 그룹들을 ChildReducer로 구현하고 쿡찌르기, 이미지 업로드 API 연동
- 독립적인 Model과 DesignSystem을 Scene에서 재사용성과 편의성을 높여 사용하기 위해 새로운 타겟 생성

## ✅ TODO
- [ ] 홈 화면 리팩토링
- [ ] 이미지 업로드 API 연동
- [ ] 쿡찌르기 API 연동
- [ ] 러브버그 타겟 생성
