### ISSUE TITLE
[Fix] 자잘한 디자인 수정

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#139]
## 🚀 Description
- 자잘한 디자인 수정

## ✅ TODO
- [ ] 그룹 최대 인원 수정
- [ ] Floating button에 shadow 추가
- [ ] 그룹 만들기 버튼명 수정
- [ ] PIC 업로드 상한선 안내 문구 추가 및 이미지 업로드 버튼명 수정

## 📸 Screenshot(optional)
<img src="https://github.com/user-attachments/assets/356a38b5-bff6-4745-8b89-3416b421c6ed" width="200" height="450">
<img src="https://github.com/user-attachments/assets/f7e9cd67-9afc-46db-a88f-48508abea5c6" width="200" height="450">
<img src="https://github.com/user-attachments/assets/c8570d68-3fe5-4f5f-b360-1ea3393b56c8" width="200" height="450">
<img src="https://github.com/user-attachments/assets/cd60de6a-5b2a-473d-bb3e-a550ffb4e08d" width="200" height="450">
