### ISSUE TITLE
[Chore] 프로젝트 기초 작업

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#18]
## 🚀 Description
- 커스텀 에러 프로토콜 정의
- Get 헬퍼 타겟 및 초기화 함수 추가
- RouteType 프로토콜 정의
- 미디어 에셋 관련 프로젝트의 특성을 고려한 MultipartFormDataKit 추가
- Tuist를 이용한 프로젝트 관리의 용이성을 위해 타입 및 함수 추가

## ✅ TODO
- [x] 에러 프로토콜 정의
- [x] Get 헬퍼 타겟 추가
- [x] RouteType 프로토콜 정의
- [x] MultipartFormDataKit 추가
- [x] Tuist를 이용한 프로젝트 관리의 용이성을 위해 타입 및 함수 추가
