### ISSUE TITLE
[Feat] 사진 앨범 기능 및 사진 접근 권한 서비스 구현

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/gabbangzip-iOS#35]
## 🚀 Description
- 사진 앨범 기능 구현 (단일, 멀티플 셀렉 대응)
- 사진 접근 권한 확인 및 요청 서비스 객체 구현
- 서비스 객체 코드 순서 통일

## ✅ TODO
- [x] 사진 앨범 기능 구현
- [x] 사진 접근 권한 확인 및 요청 서비스 객체 구현
- [x] 서비스 객체 코드 순서 통일
