### ISSUE TITLE
[Design] DesignSystem 초기 구축

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/gabbangzip-iOS#38]
## 🚀 Description
- DS 구축
  - 폰트, 컬러, 아이콘이 나오는대로 바로 구축
  - 뷰 컴포넌트들은 해당 시점에 나오는것들 추가, 나머지는 차후 이슈에서 진행 예정

## ✅ TODO
- [x] 폰트, 컬러 DS 구축
- [x] 아이콘 DS 구축
- [x] 뷰 컴포넌트 초기 구축
