### ISSUE TITLE
[Feat] 그룹 만들기 구현1

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#42]
## 🚀 Description
- 그룹 만들기 기능을 나눠서 구현. 그 중 첫 번째 작업

## ✅ TODO
- [ ] 그룹만들기 구현
- [ ] 그룹 이름 정하기 구현
- [ ] 그룹 키워드 선택 구현
- [ ] 그룹 사진 선택 구현

## 📸 Screenshot(optional)

<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/60ba8a4f-1500-4e84-abaf-33cf51d7bdb0" width="200" height="450">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/59358dff-3e6c-4ab8-8684-e60cc17b7076" width="200" height="450">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/a9c5a1e1-15b8-4c80-86fb-37b4eb084988" width="200" height="450">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/a56cc521-56c4-47a4-8c61-6287277068f5" width="200" height="450">
