### ISSUE TITLE
[Feat] 이벤트 만들기 구현

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#43]
## 🚀 Description
- 이벤트 시작 화면 구현
- 이벤트 만들기 화면 구현

## ✅ TODO
- [ ] Event Coordinator 연결
- [ ] 이벤트 시작 시 Lottie 화면 구현
- [ ] 이벤트 생성 시 사진첩에서 사진 고르기 구현
