### ISSUE TITLE
[Feat] 이벤트 투표

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#44]
## 🚀 Description
이벤트 투표 관련 피쳐 개발을 진행합니다.

## ✅ TODO
디자인
- [x] 그룹 상세 페이지
- [x] 그룹원 리스트
- [x] 투표하기
- [x] 투표 완료 페이지
- [x] 이미지 뷰어

API
- [x] 그룹 상세 페이지, 내 PIC 등록하기, 네컷 생성 완료 페이지
- [x] 이미지 뷰어
- [x] 그룹원 리스트
- [x] 투표하기, 투표 완료 페이지

기타
- [x] 코디네이터 작업

## 📸 Screenshot(optional)
<img width="1769" alt="image" src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/22907483/9f9312c0-526e-40c6-93ac-67c6a74a8bcf">
