### ISSUE TITLE
[Feat] 자동 Login 및 Refresh Token

### ISSUE THREAD

**Issue by serena0720** [mash-up-kr/gabbangzip-iOS#63]
## 🚀 Description
#57 과 연관되는 이슈입니다.

## ✅ TODO
- [ ] 자동 Login 구현
- [ ] Login완료 후 MainView(GroupView)로 이동
- [ ] AccessToken, Refresh Token 유효성 확인
- [ ] 🌼 디자인 팀에서 PICLogo 수정 완료되면 업데이트 예정입니다.
