### ISSUE TITLE
[Design] Colorset 변경 및 프레임 이미지 추가 및 기타 asset 수정

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#67]
## ✅ TODO
- [ ] Colorset 변경
- [ ] 프레임 이미지 추가
- [ ] 카테고리 background color 변경
- [ ] 카테고리 에셋 변경(색상 변경)
- [ ] SmallButton - 쿡찌르기, 투표하기 아이콘 추가

## 📸 Screenshot(optional)
![CleanShot 2024-07-01 at 19 04 22@2x](https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/429f8d42-9228-4d43-b1b0-dbb75e60935f)
![CleanShot 2024-07-01 at 19 04 35@2x](https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/56e87c18-ec97-40b6-9e3b-56f95442263a)
