### ISSUE TITLE
[Design] 디자인 시스템 수정사항 반영

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#78]
## 🚀 Description
- 디자인 시스템 수정사항 반영

## ✅ TODO
- [ ] PIC 로고 이미지 교체
- [ ] 네비게이션 바에 변경된 로고 적용
- [ ] head24 폰트 추가
- [ ] 카테고리 이미지 이름을 서버에서 사용하는 이름과 일치하도록 수정
- [ ] EtcType에 업데이트 Case에 대한 문구 수정
- [ ] Tag 수정(버튼 기능이 삭제됨)
- [ ] 포토카드 추가
- [ ] 날짜 포맷 및 String extension 추가

## 📸 Screenshot(optional)
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/c5bf3b3c-50be-44d0-b5ac-6abc7d86e143" width="200" height="450">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/4dc96ea2-6f53-48c6-a2ee-2f5967ba26f5" width="200" height="450">
<img src="https://github.com/mash-up-kr/gabbangzip-iOS/assets/42647277/4d8f0121-85a2-497d-b9b6-3961734121cf" width="200" height="450">
