### ISSUE TITLE
[Infra] CI/CD 스크립트 보완 및 깃헙 연동

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/gabbangzip-iOS#9]
## 🚀 Description
- CI/CD grunt를 이용한 스크립트 생성 및 일원화
- Github 연동을 통한 배포 시 릴리즈 커밋 자동화

## ✅ TODO
- [x] CI/CD grunt를 이용한 스크립트 생성 및 일원화
- [x] grunt를 이용한 Onboarding 환경 설정 (Github 연동 초석)
- [x] Github 연동을 통한 배포 시 릴리즈 커밋 / 푸쉬 자동화
