### ISSUE TITLE
[Hotfix] MyPage Login 수정 등

### ISSUE THREAD

**Issue by serena0720** [mash-up-kr/gabbangzip-iOS#91]
## 🚀 Description
- Login 로직 Error 타입 수정
- onAppear 시 닉네임 및 알람 설정 확인 로직 추가
> 현재 닉네임을 별도로 넣어줘야 함
- Withdraw 시 Logout 되는 문제 해결
- Firebase Client 수정
- Loading 임시뷰 삭제

## ✅ TODO
- [x] Login Error 타입 수정
- [x] onAppear 구현
- [x] @Shaered userInfo의 nickname을 가져오도록 수정
- [x] NavigationBar Backbutton 코디네이터 통해 화면 이동
- [x] Loading 임시 텍스트뷰 삭제
- [x] Withdraw의 rightButton 로직 수정
- [x] FirebaseClient 수정

## 📸 Screenshot(optional)
<img src="https://github.com/user-attachments/assets/ff2da826-948e-47ee-8573-6d427a360bde" width="300" />
