### ISSUE TITLE
[Feature] 그룹 만들기2 구현

### ISSUE THREAD

**Issue by zekexros** [mash-up-kr/gabbangzip-iOS#97]
## 🚀 Description
- #86 에 이어서 그룹 만들기2 구현(그룹 만들기는 2부작입니다ㅎㅎ)

## ✅ TODO
- [ ] 파일 업로드 API 구현
- [ ] UIPasteClient 구현
- [ ] Presigned-url을 이용한 S3 이미지 업로드 기능 구현(multipart/form-data)
- [ ] 그룹 만들기 화면들 중 사진 고르기 화면 마무리
- [ ] 그룹 만들기 화면들 중 완료 화면 및 기능 구현
- [ ] 그룹 만들기 코디네이터 구현

## 📸 Screenshot(optional)
<img src="https://github.com/user-attachments/assets/1634a8c8-a1e5-445f-8d4b-54fcc7beb372" width="200" height="450">
<img src="https://github.com/user-attachments/assets/051b223a-8a26-4dd4-a284-d9ce020992ed" width="200" height="450">
